VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsDBTrans"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public SQLStmt As String

Public Rst As Recordset
Public Sub BeginTrans()

End Sub

Public Sub CommitTrans()

End Sub

Public Sub RollBack()

End Sub





Public Function SQLExecute() As Boolean

End Function

Public Function SQLFetch() As Long

End Function


